### ISSUE TITLE
hero image doesn't work?

### ISSUE THREAD

**Issue by chronopoulos** [SimonMueller/grav-theme-pluspunkt#36]
is this theme compatible with hero images in the intro's? for example, on the home page:

```
title: Home
media_order: pcb_dark.png
hero_image: pcb_dark.png
visible: false
intro:
    enabled: true
    fullscreen: true
    text_enabled: true
    text: '(sustainable [technology) development]'
```

but the image never appears. is there a way to accomplish this?
